# Generated by Django 4.2 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '卡券类别',
                'verbose_name_plural': '卡券类别',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='佣金')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling.category', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='佣金')),
                ('card_number', models.CharField(max_length=200, verbose_name='卡号')),
                ('card_secret', models.CharField(max_length=200, verbose_name='密码')),
                ('image', models.URLField(verbose_name='核销码图片')),
                ('expire_date', models.DateField(verbose_name='过期时间')),
                ('telephone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('settled', '已结算')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('admin_remark', models.TextField(blank=True, verbose_name='管理员备注')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling.category', verbose_name='卡券类别')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling.package', verbose_name='套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-submitted_at'],
            },
        ),
    ]