# Generated by Django 4.2 on 2024-01-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='card_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='card_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.URLField(blank=True, verbose_name='核销码图片'),
        ),
    ]