# Generated by Django 4.2 on 2024-01-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0002_update_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/', verbose_name='核销码图片'),
        ),
    ]